### ISSUE TITLE
Cannot POST image files to create pins

### ISSUE THREAD

**Issue by dustinsgoodman** [realadeel/pinterest-api#5]
Pinterest's API requires uploading the image via a form data POST call. The gem currently does not support that behavior so either the `image_url` or `image_base64`. It would be nice if the gem could support the `image` option as well. See https://developers.pinterest.com/docs/api/pins

**Comment by realadeel** [comment]
Ah good feedback! I'll try to take a look this weekend.

**Comment by dustinsgoodman** [comment]
Thanks @realadeel!

**Comment by justin-rhoades** [comment]
If this project is still being maintained I'm willing to work on this. Let me know @realadeel

**Comment by realadeel** [comment]
Absolutely being maintained, at least monitored! I totally dropped the ball on @dustinsgoodman sorry but if you have a PR it'll be merged in immediately with many thanks.

**Comment by dustinsgoodman** [comment]
No worries @realadeel! I was able to create a workaround so I could use the `image_base64` parameter instead but this type of support would still be awesome. It's all about finding the time to do it. 😄 

Thanks @justin-rhoades for volunteering to take this on!

**Comment by justin-rhoades** [comment]
No worries, I will work on this over the weekend @dustinsgoodman @realadeel

**Comment by justin-rhoades** [comment]
@realadeel Just leaving a note that this is solved by #7 if you want to close the issue
